package frozenblock.wild.mod.worldgen;

import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import frozenblock.wild.mod.registry.RegisterWorldgen;
import net.minecraft.structure.pool.StructurePool;
import net.minecraft.structure.pool.StructurePoolElement;
import net.minecraft.structure.pool.StructurePools;
import net.minecraft.structure.processor.StructureProcessorLists;
import net.minecraft.util.Identifier;

public class AncientCityData {
    public AncientCityData() {
    }

    public static void init() {
    }

    static {
        StructurePools.register(new StructurePool(new Identifier("ancient_city/structures"), new Identifier("empty"), ImmutableList.of(Pair.of(StructurePoolElement.ofEmpty(), 7), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/barracks", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 4), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/chamber_1", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 4), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/chamber_2", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 4), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/chamber_3", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 4), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/sauna_1", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 4), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/small_portal_statue", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 4), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/large_ruin_1", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/medium_ruin_1", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/medium_ruin_2", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/small_ruin_1", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/small_ruin_2", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), new Pair[]{Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/large_pillar_1", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/medium_pillar_1", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1)}), StructurePool.Projection.RIGID));
        //StructurePools.register(new StructurePool(new Identifier("ancient_city/sculk"), new Identifier("empty"), ImmutableList.of(Pair.of(StructurePoolElement.ofFeature(AncientCityPlacements.SCULK_CATALYST_WITH_PATCHES_CITY), 6), Pair.of(StructurePoolElement.ofEmpty(), 1)), Projection.RIGID));
        StructurePools.register(new StructurePool(new Identifier("ancient_city/walls"), new Identifier("empty"), ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_corner_wall_1", RegisterWorldgen.ANCIENT_CITY_WALLS_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_intersection_wall_1", RegisterWorldgen.ANCIENT_CITY_WALLS_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_lshape_wall_1", RegisterWorldgen.ANCIENT_CITY_WALLS_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_1",RegisterWorldgen.ANCIENT_CITY_WALLS_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_2", RegisterWorldgen.ANCIENT_CITY_WALLS_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_1", RegisterWorldgen.ANCIENT_CITY_WALLS_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_2", RegisterWorldgen.ANCIENT_CITY_WALLS_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_3", RegisterWorldgen.ANCIENT_CITY_WALLS_DEGRADATION), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(new StructurePool(new Identifier("ancient_city/walls/no_corners"), new Identifier("empty"), ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_1", RegisterWorldgen.ANCIENT_CITY_WALLS_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_2", RegisterWorldgen.ANCIENT_CITY_WALLS_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_1", RegisterWorldgen.ANCIENT_CITY_WALLS_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_2", RegisterWorldgen.ANCIENT_CITY_WALLS_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_3", RegisterWorldgen.ANCIENT_CITY_WALLS_DEGRADATION), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(new StructurePool(new Identifier("ancient_city/city_center/walls"), new Identifier("empty"), ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/bottom", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/bottom_left_corner", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/bottom_right_corner", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/left", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/right", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/top", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/top_right_corner", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/top_left_corner", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(new StructurePool(new Identifier("ancient_city/city/entrance"), new Identifier("empty"), ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city/entrance/top_piece", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city/entrance/bottom_piece", RegisterWorldgen.ANCIENT_CITY_GENERIC_DEGRADATION), 1)), StructurePool.Projection.RIGID));
    }
}
